apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mtgmetaanalyzer-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: "{{ .Release.Namespace }}-https-redirect-mw@kubernetescrd"
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: "mtgmeta-affinity"
    traefik.ingress.kubernetes.io/service.sticky.cookie.domain: "{{ .Values.ingress.domain }}"
    traefik.ingress.kubernetes.io/service.sticky.cookie.path: "/"
    traefik.ingress.kubernetes.io/service.sticky.cookie.maxage: "10800"
    traefik.ingress.kubernetes.io/service.sticky.cookie.httponly: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.samesite: "lax"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - "{{ .Values.ingress.domain }}"
        - "www.{{ .Values.ingress.domain }}"
      secretName: mtgmetaanalyzer-cert-tls
  rules:
    - host: "{{ .Values.ingress.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mtgmetaanalyzer-service
                port:
                  number: 3000

    - host: "www.{{ .Values.ingress.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mtgmetaanalyzer-service
                port:
                  number: 3000
