apiVersion: v1
kind: Service
metadata:
  name: mtgmetaanalyzer-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
    - name: ws
      port: 3210
      targetPort: ws
      protocol: TCP
  selector:
    app: mtgmetaanalyzer
